#ifndef AIRLY_INCLUDE_WEB_THINGS_CONFIG_H_
#define AIRLY_INCLUDE_WEB_THINGS_CONFIG_H_

#if !defined(LARGE_JSON_BUFFERS)
#define LARGE_JSON_BUFFERS 1
#endif
#if !defined(ARDUINOJSON_USE_LONG_LONG)
#define ARDUINOJSON_USE_LONG_LONG 1
#endif

#endif  // AIRLY_INCLUDE_WEB_THINGS_CONFIG_H_
