name: CI

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - v*
  pull_request:

jobs:
  lint:
    name: 🎨 Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install code formatter
        run: sudo apt-get install clang-format
      - name: Check code style
        run: |
          find include -type f | xargs clang-format --dry-run -Werror
          find src -type f | xargs clang-format --dry-run -Werror
          find test -type f | xargs clang-format --dry-run -Werror
      - name: Use Node.js
        uses: actions/setup-node@v2
      - name: Install markdownlint
        run: npm install markdownlint-cli
      - name: Check Markdown files
        run: markdownlint .
